logging:
  level:
    org.springframework.cloud.dataflow.module.deployer.yarn: DEBUG
    org.springframework.statemachine: DEBUG
server:
  port: 9393
management:
  contextPath: /management
spring:
  main:
    show_banner: false
  application:
    name: spring-cloud-dataflow-admin
  cloud:
    dataflow:
      yarn:
        version: "@project.version@"
    