logging:
  level:
    org.springframework: WARN
    org.apache.hadoop: OFF
spring:
  main:
    show_banner: false
  cloud:
    dataflow:
      yarn:
        version: "@project.version@"
  yarn:
    appType: DATAFLOW
    client:
      clientClass: org.springframework.yarn.client.DefaultApplicationYarnClient
